// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvgbsdhftlnzyxboxrae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2Z2JzZGhmdGxuenl4Ym94cmFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjU3MTcsImV4cCI6MjA2NTUwMTcxN30.3ho2oUbm3kEXORbM4gDh9YnJbTr7v_QXIQK4JKulUPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);